### PR TITLE
Revert "Base should be at the bottom of libs"

### PR DESCRIPTION
**Pull request by solvingj**
Reverts bincrafters/conan-abseil#2
@r-darwish reported a regression of working linkage due to this change. 
Reverting until we can reconcile which builds are failing for @fulara vs @r-darwish .

### CODE REVIEW

**Comment by kepam** [comment]
Without base on the bottom it not working on rhel6, rhel7, gcc4.9.
If we try to use anything that needs linkage we get:

```
.conan/data/abseil/20180223/external/stable/package/dec8fe57f12bc5cdfa459cd1331587bb6388e68f/lib/libabsl_strings.a(numbers.cc.o): In function `absl::SimpleAtob(absl::string_view, bool*)':
numbers.cc:(.text+0x5bb): undefined reference to `absl::raw_logging_internal::RawLog(absl::LogSeverity, char const*, int, char const*, ...)'
```

**Comment by r-darwish** [comment]
We're using GCC 8.1.1 on Arch Linux

**Comment by solvingj** [comment]
So do we actually specify different link order based on GCC version?  That sounds pretty funny to me if so, but maybe it's the only way.

**Comment by r-darwish** [comment]
I don't think it's necessarily related to the GCC version. There are probably many other variables that we didn't take into account. I'll try to tweak some stuff in our setup tomorrow and maybe I'll have a better diagnostic.

**Comment by fulara** [comment]
@r-darwish please provide more information on whats exactly fails to link after this.
right now we are forced to use locally hacked version of this package. 
I will provide a minimal example tomorrow.

**Comment by r-darwish** [comment]
```
/home/roeyd/.conan/data/abseil/20180223/bincrafters/stable/package/2c88fee066945268a9b2c2034c22cd34d7669af7/lib/libabsl_base.a(sysinfo.cc.o):sysinfo.cc:function absl::base_internal::NumCPUs(): error: undefined reference to 'AbslInternalSpinLockWake'
/home/roeyd/.conan/data/abseil/20180223/bincrafters/stable/package/2c88fee066945268a9b2c2034c22cd34d7669af7/lib/libabsl_base.a(sysinfo.cc.o):sysinfo.cc:function absl::base_internal::NumCPUs(): error: undefined reference to 'absl::base_internal::SpinLockWait(std::atomic<unsigned int>*, int, absl::base_internal::SpinLockWaitTransition const*, absl::base_internal::SchedulingMode)'
/home/roeyd/.conan/data/abseil/20180223/bincrafters/stable/package/2c88fee066945268a9b2c2034c22cd34d7669af7/lib/libabsl_base.a(sysinfo.cc.o):sysinfo.cc:function absl::base_internal::NominalCPUFrequency(): error: undefined reference to 'AbslInternalSpinLockWake'
/home/roeyd/.conan/data/abseil/20180223/bincrafters/stable/package/2c88fee066945268a9b2c2034c22cd34d7669af7/lib/libabsl_base.a(sysinfo.cc.o):sysinfo.cc:function absl::base_internal::NominalCPUFrequency(): error: undefined reference to 'absl::base_internal::SpinLockWait(std::atomic<unsigned int>*, int, absl::base_internal::SpinLockWaitTransition const*, absl::base_internal::SchedulingMode)'
collect2: error: ld returned 1 exit status
```
This is what we're getting
